name: Tag and Release on Master Merge

on:
  push:
    branches:
      - master

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Get Version from Composer.json
        run: echo ::set-output name=version::$(php -r "echo json_decode(file_get_contents('composer.json'), true)['version'];")
        id: get_version
      
      - name: Create Git Tag
        uses: anothrNick/github-tag-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.get_version.outputs.version }}
          message: "Tagging commit ${{ github.sha }}"
      
      - name: Create GitHub Release
        uses: actions/create-release@v1.0.1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            ${{ steps.drafter.outputs.changelog }}
          draft: false
          prerelease: false
